'use strict';
(() => {
  const root = document.getElementById('app');
  const saved = (key) => { try { return sessionStorage.getItem(key); } catch { return null; } };
  const save = (key, value) => { try { if (value == null) sessionStorage.removeItem(key); else sessionStorage.setItem(key, value); } catch {} };
  let lang = new URLSearchParams(location.search).get('lang') || saved('echo-lang') || (navigator.language.startsWith('zh') ? 'zh' : 'en');
  let token = saved('echo-token'), user = null, room = null, authMode = 'register', chosenRole = 'judge', busy = false;
  let polling = false, signature = '', clockOffset = 0, connectionLost = false;
  const drafts = {}, params = new URLSearchParams(location.search);
  const invitation = (params.get('room') || saved('echo-room') || '').toUpperCase();
  const base = globalThis.ECHO_API_BASE || '';
  const t = (zh, en) => lang === 'zh' ? zh : en;
  const e = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
  const questions = () => t(['如果今晚只剩你一个人，你会做什么？','有没有一个你总改不掉的小习惯？','说说今天一个很小的瞬间。','什么声音会让你突然安心？','如果可以回到昨天，你会改变什么？','用一句话，说服我你是刚才那个人。'], ['What would you do with an evening entirely to yourself?','What is one little habit you cannot shake?','Tell me about one tiny moment from today.','What sound makes you feel safe?','If you could return to yesterday, what would you change?','In one sentence, convince me you are the person from before.']);
  const errors = {
    invalid_username:['用户名用 3–24 位英文字母、数字或下划线。','Use 3–24 letters, numbers, or underscores.'], invalid_password:['密码需要 10–128 个字符。','Use a password of 10–128 characters.'],
    username_taken:['这个用户名已被使用。','This username is already taken.'], wrong_credentials:['用户名或密码不正确。','Incorrect username or password.'], login_required:['请先登录。','Please sign in first.'],
    session_expired:['登录已过期，请重新登录。','Your session expired. Please sign in again.'], invalid_room:['请输入 8 位房间号。','Enter an 8-character room code.'], room_expired:['房间不存在或已过期。','This room does not exist or has expired.'],
    room_full:['这个房间已有两位玩家。','This room already has two players.'], not_in_room:['你不在这个房间内。','You are not a member of this room.'], wrong_phase:['回合已更新，请查看当前状态。','The round changed. Check the current state.'],
    room_changed:['房间刚刚更新，请重试。','The room just changed. Please try again.'], rate_limited:['操作过于频繁或试玩额度已用完，请稍后再试。','Too many requests or the playtest allowance is reached. Try again later.'],
    ai_unconfigured:['AI 还未接通，请稍后再来。','The AI is not connected yet. Please return later.'], ai_balance:['AI 服务余额不足，本轮尚未公布。','The AI service has insufficient credit. This round has not been revealed.'],
    ai_key:['AI 服务暂时无法验证，本轮尚未公布。','The AI service could not authenticate. This round has not been revealed.'], ai_unavailable:['AI 暂时没有回应，可以重试本轮。','The AI did not respond. You can retry this round.'],
    ai_timeout:['AI 回应超时，可以重试本轮。','The AI response timed out. You can retry this round.'], ai_empty:['AI 未返回有效回答，请重试。','The AI returned no answer. Please retry.'],
    retry_limit:['本轮已达到重试上限，请重新开局。','This round reached its retry limit. Start a new game.'], answer_timeout:['发言超时，本局已结束。','The answer deadline passed. This game has ended.'],
    service_unavailable:['暂时无法连接回声室，请稍后重试。','Echo Room is temporarily unavailable. Please try again.'], invalid_text:['请填写 1–140 个字符。','Enter 1–140 characters.'],
    network:['连接暂时中断，正在重连。输入的文字会保留。','Connection interrupted. Reconnecting; your draft is preserved.'],
  };
  const message = code => { const pair = errors[code] || errors.service_unavailable; return t(...pair); };
  let noticeTimer;
  function notice(text) { const el = document.getElementById('notice'); el.textContent = text; el.hidden = false; clearTimeout(noticeTimer); noticeTimer = setTimeout(() => el.hidden = true, 6000); }
  async function api(path, data) {
    const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 35000);
    try {
      const response = await fetch(base + path, { method: data === undefined ? 'GET' : 'POST', headers: { ...(data !== undefined ? { 'Content-Type': 'application/json' } : {}), ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: data === undefined ? undefined : JSON.stringify(data), signal: controller.signal, cache: 'no-store', credentials: 'omit' });
      const result = await response.json();
      if (!response.ok) { const error = new Error(result.error || 'service_unavailable'); error.status = response.status; throw error; } return result;
    } catch (error) { if (!error.status) throw new Error('network'); throw error; } finally { clearTimeout(timer); }
  }
  function rules() { return `<details class="rules"><summary>${t('怎么玩','How to play')}</summary><p>${t('两位真人分别担任判断者和发言者，另有一位 AI。判断者每轮提出一个问题；发言者在 90 秒内回答。前三轮 AI 原样复读，后三轮根据之前的语气独立回答。每轮两条消息一起公布，A/B 身份整局不变。第六轮后，你有 20 秒选出真人。选对则两位真人获胜，选错或超时则 AI 获胜。','One person judges; the other answers. An AI takes the remaining anonymous seat. The judge asks one question per round. The human has 90 seconds to answer. The AI copies the first three answers, then writes its own for three rounds. Answers are revealed together. A/B identities stay fixed. After round six, the judge has 20 seconds to identify the human. A correct choice wins for both humans; a wrong choice or timeout wins for the AI.')}</p><p>${t('请勿发送个人敏感信息。你的对话会用于本局 DeepSeek 推理；房间 30 分钟后过期，账号仅用于登录。原型暂不支持找回密码，请妥善记住。','Please avoid sensitive personal information. Your dialogue is sent to DeepSeek for this game. Rooms expire after 30 minutes. Accounts are only used to sign in. Password recovery is not available in this prototype.')}</p></details>`; }
  function header() { document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'; document.getElementById('language').textContent = t('EN', '中文'); const logout = document.getElementById('logout'); logout.hidden = !user; logout.textContent = t('退出', 'Sign out'); root.removeAttribute('aria-busy'); }
  function auth() {
    root.innerHTML = `<section class="welcome"><div><p class="eyebrow">EXPERIMENT 001 / IDENTITY</p><h1>${t('两道回声。<br>一个<em>真人。</em>','Two echoes.<br>One <em>human.</em>')}</h1><p class="intro">${t('起初，他们说着相同的话。<br>后来，其中一个开始有了自己的声音。<br>你还能认出谁是谁吗？','At first, they say exactly the same thing.<br>Then one finds a voice of its own.<br>Can you still tell who is who?')}</p><div class="echo-diagram"><div class="mini-channel"><span>CHANNEL A</span><p>${t('“你还在听吗？”','“Are you still listening?”')}</p></div><div class="mini-channel"><span>CHANNEL B</span><p>${t('“你还在听吗？”','“Are you still listening?”')}</p></div></div><div class="rules-inline"><span><b>02</b> ${t('位玩家','players')}</span><span><b>01</b> AI</span><span><b>20s</b> ${t('做出判断','to decide')}</span></div></div><div class="panel"><div class="auth-switch"><button type="button" data-auth="register" aria-pressed="${authMode === 'register'}">${t('注册', 'Register')}</button><button type="button" data-auth="login" aria-pressed="${authMode === 'login'}">${t('登录', 'Sign in')}</button></div><p>${t('叫上一位朋友，进入同一个房间。','Bring a friend. Meet in the same room.')}</p>${invitation ? `<p class="badge">${t('受邀房间','Invitation')} ${e(invitation)}</p>` : ''}<form id="auth-form"><label for="username">${t('用户名','Username')}</label><input id="username" name="username" required minlength="3" maxlength="24" pattern="[A-Za-z0-9_]{3,24}" autocomplete="username" autocapitalize="none" spellcheck="false" placeholder="${t('英文字母、数字或下划线','Letters, numbers, underscores')}"><label for="password">${t('密码','Password')}</label><input id="password" name="password" type="password" required minlength="10" maxlength="128" autocomplete="${authMode === 'register' ? 'new-password' : 'current-password'}" placeholder="${t('至少 10 个字符','At least 10 characters')}"><button class="primary full" type="submit">${authMode === 'register' ? t('注册并进入','Create account') : t('进入回声室','Enter Echo Room')}</button><p class="fine">${t('不需要邮箱。你的用户名不会显示给对面的玩家。','No email required. Your username is hidden from the other player.')}</p></form>${rules()}</div></section>`;
    root.querySelectorAll('[data-auth]').forEach(b => b.onclick = () => { authMode = b.dataset.auth; auth(); });
    document.getElementById('auth-form').onsubmit = async ev => { ev.preventDefault(); if (busy) return; const values = new FormData(ev.currentTarget); await run(async () => { const result = await api('/api/auth/' + authMode, { username: values.get('username'), password: values.get('password') }); token = result.token; user = result.user; save('echo-token', token); render(); if (invitation) document.getElementById('join-code').value = invitation; }); };
  }
  function lobby() {
    root.innerHTML = `<section><div class="section-header"><div><p class="eyebrow">THE WAITING ROOM</p><h1>${t('谁在对面？','Who is on the other side?')}</h1><p>${t('邀请一位朋友，让第三个声音加入你们。','Invite a friend. Let a third voice join you.')}</p></div><span class="badge">${e(user.username)}</span></div><div class="lobby-grid"><div class="panel"><h2>${t('创建房间','Create a room')}</h2><p>${t('选择这一局的角色。你的朋友将担任另一个角色。','Choose your role. Your friend takes the other one.')}</p><div class="role-picks"><button data-role="judge" aria-pressed="${chosenRole === 'judge'}"><span>${t('判断者','The judge')}</span><small>${t('提问、观察、找出真人','Ask, observe, find the human')}</small></button><button data-role="speaker" aria-pressed="${chosenRole === 'speaker'}"><span>${t('发言者','The speaker')}</span><small>${t('回答问题，守住自己的声音','Answer; hold on to your voice')}</small></button></div><button class="primary full" id="create">${t('创建双人房间','Create two-player room')}</button></div><div class="panel"><h2>${t('加入朋友','Join a friend')}</h2><p>${t('输入朋友分享的 8 位房间号。','Enter the 8-character code your friend shared.')}</p><form id="join-form"><label for="join-code">${t('房间号','Room code')}</label><div class="join-row"><input id="join-code" required maxlength="8" minlength="8" pattern="[A-Za-z2-9]{8}" autocomplete="off" spellcheck="false" placeholder="XXXXXXXX" value="${e(invitation)}"><button class="secondary" type="submit">${t('加入','Join')}</button></div></form><div class="hint-box">${t('两个人用各自的设备或浏览器登录。<br>一局约 5 分钟；最后 20 秒做出判断。','Sign in on separate devices or browsers.<br>A game takes about 5 minutes. Decide in the last 20 seconds.')}</div></div></div>${rules()}</section>`;
    root.querySelectorAll('[data-role]').forEach(b => b.onclick = () => { chosenRole = b.dataset.role; lobby(); });
    document.getElementById('create').onclick = () => run(async () => setRoom((await api('/api/rooms', { role: chosenRole })).room));
    document.getElementById('join-form').onsubmit = ev => { ev.preventDefault(); const code = document.getElementById('join-code').value.trim().toUpperCase(); run(async () => setRoom((await api('/api/rooms/' + code + '/join', {})).room)); };
  }
  const wave = pending => `<div class="wave ${pending ? 'pending' : ''}" aria-hidden="true">${'<i></i>'.repeat(23)}</div>`;
  function channels(round, pending = false) { return `<div class="channels">${['A', 'B'].map(seat => `<article class="channel" aria-label="${t('匿名席位','Anonymous seat')} ${seat}"><div class="channel-head"><span class="channel-name">${seat}</span><span class="meta">CHANNEL ${seat}</span></div>${round ? `<p class="speech">${e(round[seat])}</p>` : `${wave(pending)}<p class="empty-speech">${t('等待回声','Waiting for an echo')}</p>`}</article>`).join('')}</div>`; }
  function history() { return room.rounds.length ? `<details class="history" ${room.status === 'finished' ? 'open' : ''}><summary>${t('之前的对话','Conversation history')} (${room.rounds.length})</summary>${room.rounds.map(r => `<section class="history-item"><h4>${String(r.number).padStart(2, '0')} / ${e(r.question)}</h4><div class="history-pair"><div><b>A</b>${e(r.A)}</div><div><b>B</b>${e(r.B)}</div></div></section>`).join('')}</details>` : ''; }
  function gameplay() {
    const r = room, judge = r.role === 'judge', n = r.current?.number || Math.min(r.rounds.length + 1, 6), last = r.rounds.at(-1);
    let content = '', controls = '', title = r.current?.question || last?.question || t('连接已建立。','Connection established.');
    if (r.status === 'waiting') {
      content = `<div class="waiting"><p class="eyebrow">AWAITING SECOND HUMAN</p><h2>${t('另一把椅子，还空着。','The other chair is still empty.')}</h2><p>${t('把房间号发给朋友。两位玩家到齐后即可开始。','Send this code to your friend. Begin when both players are here.')}</p><div class="large-code">${e(r.code)}</div><button id="invite" class="primary">${t('复制邀请链接','Copy invitation link')}</button><p class="fine">${t('请使用不同账号加入。房间保留 30 分钟。','Join with different accounts. The room lasts for 30 minutes.')}</p></div>`;
    } else if (r.status === 'cancelled') {
      content = `<div class="result"><p class="eyebrow">SIGNAL LOST</p><h2>${t('本局已结束','This game has ended')}</h2><p>${r.error ? e(message(r.error)) : t('一位玩家离开了房间。','A player left the room.')}</p><button id="back" class="primary">${t('返回大厅','Return to lobby')}</button></div>`;
    } else {
      if (r.status === 'finished') {
        const won = r.result.winner === 'humans';
        content += `<section class="result"><p class="eyebrow">${won ? 'HUMAN RECOGNIZED' : 'THE ECHO REMAINS'}</p><h2>${won ? t('你认出了那个真人。','You found the human.') : r.result.vote ? t('这一次，回声骗过了你。','This time, the echo fooled you.') : t('时间到了，回声留下了。','Time ran out. The echo remains.')}</h2><div class="result-identities"><span>${e(r.result.humanSeat)} / ${t('真人','Human')}</span><span>${e(r.result.aiSeat)} / DeepSeek AI</span></div><p>${t('前三轮，两道声音完全相同。从第四轮起，AI 开始独立回答。','For three rounds, the voices were identical. From round four, the AI answered for itself.')}</p><button id="back" class="primary">${t('再开一局','Start another game')}</button></section>`;
      }
      content += `<section class="question"><span class="meta">${t('问题','QUESTION')} ${String(r.current?.number || last?.number || 1).padStart(2, '0')} / 06</span><h2>${e(title)}</h2></section>`;
      content += channels(r.current ? null : last, ['answering', 'generating', 'releasing'].includes(r.status));
      if (r.status === 'question' && judge) controls = `<form id="question-form"><label for="question-text">${t('下一轮，你想问什么？','What would you like to ask next?')} <span class="meta">${n} / 6</span></label><textarea id="question-text" required maxlength="140" placeholder="${e(questions()[n - 1])}">${e(drafts['q' + n] || '')}</textarea><div class="control-bottom"><button type="button" id="suggest" class="link-button">${t('用这个问题','Use suggested question')}</button><button class="primary" type="submit">${t('向两人提问','Ask both voices')}</button></div></form>`;
      else if (r.status === 'question') controls = `<p>${t('等待判断者提出下一个问题。','Waiting for the judge’s next question.')}</p>`;
      else if (r.status === 'answering' && !judge) controls = `<form id="answer-form"><label for="answer-text">${t('用你的方式回答','Answer in your own words')} · <span data-timer></span></label><textarea id="answer-text" required maxlength="140" placeholder="${t('想到什么，就说什么。','Say what comes to mind.')}">${e(drafts['a' + n] || '')}</textarea><div class="control-bottom"><span class="fine">${t('最多 140 个字符','Up to 140 characters')}</span><button class="primary" type="submit">${t('提交回答','Submit answer')}</button></div></form>`;
      else if (['answering', 'generating', 'releasing'].includes(r.status)) controls = `<p>${t('等待两道声音。两条消息将同时公布。','Waiting for both voices. Both messages will appear together.')}</p>`;
      else if (r.status === 'ai_error') controls = `<p class="error-text">${e(message(r.error))}</p>${!judge ? `<button class="secondary" id="retry">${t('重试本轮','Retry this round')}</button>` : `<p>${t('等待发言者重试；此时没有开始判断倒计时。','Waiting for the speaker to retry. The decision timer has not started.')}</p>`}`;
      else if (r.status === 'deciding') controls = `<p class="eyebrow">MAKE YOUR CHOICE</p><h2>${judge ? t('哪一位是真人？','Which one is human?') : t('等待最后的判断。','Waiting for the final choice.')}</h2><div class="timer mobile-timer" data-timer></div>${judge ? `<div class="vote-buttons"><button class="vote-button" data-vote="A">${t('A 是真人','A is human')}</button><button class="vote-button" data-vote="B">${t('B 是真人','B is human')}</button></div>` : ''}`;
    }
    root.innerHTML = `<section><div class="room-top"><div class="room-actions"><span class="meta">ROOM</span><span class="room-code">${e(r.code)}</span><button class="text-button" id="copy-code">${t('复制','Copy')}</button></div><div class="room-actions"><div class="progress" aria-label="${r.rounds.length} / 6">${Array.from({ length: 6 }, (_, i) => `<span class="${i < r.rounds.length ? 'done' : ''}"></span>`).join('')}</div><button class="text-button" id="leave">${t('离开房间','Leave room')}</button></div></div><div class="room-layout"><div class="room-main">${content}<section class="control-area" aria-live="polite">${controls}</section>${history()}</div><aside class="sidebar"><p class="eyebrow">YOUR ROLE</p><h3>${judge ? t('判断者','The judge') : t('发言者','The speaker')}</h3><p>${judge ? t('提问，观察两边的声音。<br>你要找出那个真实的人。','Ask questions. Watch both voices.<br>Find the real person.') : t('自然地回答问题。<br>让判断者听见你的声音。','Answer naturally.<br>Help the judge recognize your voice.')}</p><hr><span class="meta">${t('游戏进度','PROGRESS')}</span><div class="timer">${String(r.rounds.length).padStart(2, '0')}<span style-free="true" class="meta"> / 06</span></div><p>${t('前三轮：完全复读<br>后三轮：AI 独立回答<br>最后：20 秒判断','First 3: exact echoes<br>Next 3: independent answers<br>Finally: 20 seconds to decide')}</p><hr><p>${t('A/B 身份整局固定。两条回答在同一时刻公布。','A/B identities stay fixed. Both answers are revealed together.')}</p></aside></div></section>`;
    document.getElementById('leave').onclick = () => run(async () => { if (!['finished', 'cancelled'].includes(room.status) && !confirm(t('离开会结束本局，确定离开吗？','Leaving will end this game. Leave?'))) return; await api('/api/rooms/' + room.code + '/leave', {}); clearRoom(); });
    document.getElementById('copy-code').onclick = () => copy(r.code);
    const inviteButton = document.getElementById('invite'); if (inviteButton) inviteButton.onclick = () => { const url = new URL(location.href); url.search = ''; url.searchParams.set('room', r.code); url.searchParams.set('lang', lang); copy(url.href); };
    const back = document.getElementById('back'); if (back) back.onclick = clearRoom;
    const q = document.getElementById('question-form'); if (q) { const input = document.getElementById('question-text'); input.oninput = () => drafts['q' + n] = input.value; document.getElementById('suggest').onclick = () => { input.value = questions()[n - 1]; drafts['q' + n] = input.value; }; q.onsubmit = ev => { ev.preventDefault(); action('question', { text: input.value, round: n }); }; }
    const a = document.getElementById('answer-form'); if (a) { const input = document.getElementById('answer-text'); input.oninput = () => drafts['a' + n] = input.value; a.onsubmit = ev => { ev.preventDefault(); action('answer', { text: input.value, round: n }); }; }
    const retry = document.getElementById('retry'); if (retry) retry.onclick = () => action('retry', { round: n });
    root.querySelectorAll('[data-vote]').forEach(b => b.onclick = () => action('vote', { seat: b.dataset.vote }));
    tick();
  }
  async function copy(value) { try { await navigator.clipboard.writeText(value); notice(t('已复制','Copied')); } catch { notice(value); } }
  function render() { header(); if (!user) auth(); else if (!room) lobby(); else gameplay(); }
  function clearRoom() { room = null; signature = ''; save('echo-room', null); const url = new URL(location.href); url.searchParams.delete('room'); historyReplace(url); render(); }
  function historyReplace(url) { window.history.replaceState(null, '', url); }
  function setRoom(value) { room = value; clockOffset = value.serverNow - Date.now(); save('echo-room', value.code); const next = JSON.stringify({ ...value, serverNow: 0 }); if (signature !== next) { signature = next; render(); } }
  async function run(fn) { if (busy) return; busy = true; root.querySelectorAll('button[type=submit],#create,#retry,[data-vote]').forEach(b => b.disabled = true); try { await fn(); } catch (err) { notice(message(err.message)); if (err.status === 401 && user) { token = null; user = null; room = null; save('echo-token', null); render(); } } finally { busy = false; root.querySelectorAll('button[type=submit],#create,#retry,[data-vote]').forEach(b => b.disabled = false); } }
  const action = (name, data) => run(async () => { const code = room.code; const result = await api('/api/rooms/' + code + '/' + name, data); if (room?.code === code) setRoom(result.room); });
  async function poll() {
    if (!room || polling || document.hidden || ['finished', 'cancelled'].includes(room.status)) return;
    polling = true; const code = room.code;
    try { const result = await api('/api/rooms/' + code); if (room?.code === code) setRoom(result.room); if (connectionLost) notice(t('已重新连接','Reconnected')); connectionLost = false; }
    catch (error) { if (!connectionLost) notice(message(error.message)); connectionLost = true; if ([401, 403, 404].includes(error.status)) { if (error.status === 401) { token = null; user = null; save('echo-token', null); } clearRoom(); } }
    finally { polling = false; }
  }
  function tick() { if (!room) return; const deadline = room.status === 'deciding' ? room.decisionDeadline : room.current?.answerDeadline; if (!deadline) return; const remaining = Math.max(0, Math.ceil((deadline - Date.now() - clockOffset) / 1000)); root.querySelectorAll('[data-timer]').forEach(el => { el.textContent = remaining + 's'; el.classList.toggle('urgent', remaining <= 5); }); }
  document.getElementById('language').onclick = () => { lang = lang === 'zh' ? 'en' : 'zh'; save('echo-lang', lang); render(); };
  document.getElementById('logout').onclick = () => run(async () => { if (room && !['finished', 'cancelled'].includes(room.status)) { if (!confirm(t('退出会结束本局，确定吗？','Signing out ends this game. Continue?'))) return; await api('/api/rooms/' + room.code + '/leave', {}); } await api('/api/auth/logout', {}); token = null; user = null; room = null; signature = ''; save('echo-token', null); save('echo-room', null); render(); });
  async function init() {
    if (token) { try { user = (await api('/api/me')).user; const code = saved('echo-room'); if (code) { try { setRoom((await api('/api/rooms/' + code)).room); } catch { save('echo-room', null); } } } catch (error) { if (error.status === 401) { token = null; save('echo-token', null); } else notice(message(error.message)); } }
    render(); setInterval(poll, 900); setInterval(tick, 200); document.addEventListener('visibilitychange', () => { if (!document.hidden) poll(); });
    if (document.modelContext?.registerTool) { try { await document.modelContext.registerTool({ name: 'read_echo_room', description: 'Read the visible game phase and anonymous conversation for the signed-in player. Does not reveal hidden identities before the result.', inputSchema: { type: 'object', properties: {}, additionalProperties: false }, annotations: { readOnlyHint: true, untrustedContentHint: true }, execute: async input => { if (input && Object.keys(input).length) throw new Error('No arguments allowed'); if (room) await poll(); return room ? { code: room.code, role: room.role, status: room.status, rounds: room.rounds, result: room.result || null } : { status: user ? 'lobby' : 'signed_out' }; } }); } catch {} }
  }
  init();
})();
